name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  deployments: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install and Build Vite App
        working-directory: ./my-math-app
        run: |
          npm install
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          # 👇 방금 깃허브에 만든 시크릿 이름으로 변경
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATH_SECRET_APP }}" 
          channelId: live
          # 👇 새로운 파이어베이스 프로젝트 ID로 변경
          projectId: math-secret-app